// src/entities/tooltip/ui/GearTooltip.tsx
import { clsx } from "@/shared/util";
import { Gear } from "@malib/gear";
import Attributes from "./Attributes";
import { DiffExtra, DiffExtraArea } from "./DiffExtra";
import DotLine from "./DotLine";
import Frame from "./Frame";
import Grade from "./Grade";
import Icon from "./Icon";
import Incline from "./Incline";
import { ReqArea, ReqLev, ReqLine, ReqStat } from "./Reqs";
import Spacer from "./Spacer";
import Stars from "./Stars";
import { IconArea, InclineReqArea, SummaryArea } from "./SummaryArea";
import { NameTitle, SoulTitle, TitleGroup } from "./Titles";
import styles from "./tooltip.module.css";
import { JobReq } from "./JobReq";

type Incline =
  | {
      mode: "attack";
      attack: number;
    }
  | {
      mode: "combat";
      combat: number;
    }
  | {
      mode: "attack_combat";
      attack: number;
      combat: number;
    };

export default function GearTooltip({
  gear,
  incline = { mode: "attack", attack: 0 },
  cannot = {},
  diff = { pdd: 0, bdr: 0, igpddr: 0 },
  className,
}: Readonly<{
  gear: Gear;
  incline?: Incline;
  cannot?: {
    level?: boolean;
    str?: boolean;
    dex?: boolean;
    int?: boolean;
    luk?: boolean;
    job?: boolean;
  };
  diff?: {
    pdd: number;
    bdr: number;
    igpddr: number;
  };
  className?: string;
}>) {
  return (
    <Frame className={clsx(styles.pixelated, className)}>
      <Stars star={gear.star} maxStar={gear.maxStar} color={gear.starScroll ? "blue" : "yellow"} />
      <TitleGroup>
        <SoulTitle soul={gear.soul} />
        <NameTitle name={gear.name} scrollUpgradeCount={gear.scrollUpgradeCount} color="white" />
      </TitleGroup>
      <Spacer height={4} />
      <Grade grade={gear.potentialGrade} specialGrade={gear.attributes.specialGrade} />
      <Attributes
        only={gear.attributes.only}
        trade={gear.attributes.trade}
        onlyEquip={gear.attributes.onlyEquip}
        share={gear.attributes.share}
        blockGoldenHammer={gear.attributes.blockGoldenHammer}
        canPotential={gear.attributes.canPotential}
      />
      <Spacer height={10} />
      <DotLine />
      <Spacer height={6} />
      <SummaryArea>
        <IconArea>
          <Icon
            icon={gear.shapeIcon}
            grade={Math.max(gear.potentialGrade, gear.additionalPotentialGrade)}
            newBonus={false}
          />
        </IconArea>
        <InclineReqArea>
          {incline.mode === "attack" ? (
            <Incline label="공격력 증가량" diff={incline.attack} />
          ) : null}
          {incline.mode === "combat" ? (
            <Incline label="전투력 증가량" diff={incline.combat} />
          ) : null}
          {incline.mode === "attack_combat" ? (
            <>
              <Incline label="공격력 증가량" diff={incline.attack} small />
              <Incline label="전투력 증가량" diff={incline.combat} small />
            </>
          ) : null}
          <Spacer height={1} />
          <ReqArea>
            <ReqLine>
              <ReqLev
                value={gear.req.level}
                decrease={gear.baseOption.reqLevelDecrease + gear.addOption.reqLevelDecrease}
                can
              />
            </ReqLine>
            <Spacer height={9} />
            <ReqLine>
              <ReqStat type="str" value={gear.req.str} can={!cannot?.str} />
              <ReqStat type="luk" value={gear.req.luk} can={!cannot?.luk} />
            </ReqLine>
            <Spacer height={3} />
            <ReqLine>
              <ReqStat type="dex" value={gear.req.dex} can={!cannot?.dex} />
              <ReqStat type="int" value={gear.req.int} can={!cannot?.int} />
            </ReqLine>
          </ReqArea>
        </InclineReqArea>
      </SummaryArea>
      <Spacer height={5} />
      <DiffExtraArea>
        <DiffExtra type="pdd" value={diff.pdd} />
        <DiffExtra type="bdr" value={diff.bdr} percent />
        <DiffExtra type="igpddr" value={diff.igpddr} percent />
      </DiffExtraArea>
      <Spacer height={3} />
      <JobReq reqJob={gear.req.job} gearType={gear.type} can />
    </Frame>
  );
}

// src/entities/gear-tooltip/ui/GearTooltip.svelte
<script lang="ts">
	import type { Gear } from '@malib/gear';
	import Attributes from './components/Attributes.svelte';
	import DotLine from './components/DotLine.svelte';
	import Frame from './components/Frame.svelte';
	import Grade from './components/Grade.svelte';
	import Spacer from './components/Spacer.svelte';
	import Stars from './components/Stars.svelte';
	import Icon from './components/summary/icon/Icon.svelte';
	import IconWrapper from './components/summary/icon/IconWrapper.svelte';
	import Incline from './components/summary/Incline.svelte';
	import ReqLevel from './components/summary/req/ReqLevel.svelte';
	import ReqRow from './components/summary/req/ReqRow.svelte';
	import ReqStat from './components/summary/req/ReqStat.svelte';
	import ReqWrapper from './components/summary/req/ReqWrapper.svelte';
	import SummaryDetailWrapper from './components/summary/SummaryDetailWrapper.svelte';
	import SummaryWrapper from './components/summary/SummaryWrapper.svelte';
	import NameTitle from './components/title/NameTitle.svelte';
	import SoulTitle from './components/title/SoulTitle.svelte';
	import TitleWrapper from './components/title/TitleWrapper.svelte';
	import './tooltip.css';
	import DiffExtraWrapper from './components/summary/diff/DiffExtraWrapper.svelte';
	import DiffExtra from './components/summary/diff/DiffExtra.svelte';
	import JobReq from './components/JobReq.svelte';
	import { getExtraJobReqString } from '../model/strings';

	let {
		gear,
		incline,
		cannot = {},
		diff = { pdd: 0, bdr: 0, igpddr: 0 }
	}: {
		gear: Gear;
		incline: { attack: number } | { combat: number } | { attack: number; combat: number };
		cannot?: {
			level?: boolean;
			str?: boolean;
			dex?: boolean;
			int?: boolean;
			luk?: boolean;
			job?: boolean;
		};
		diff?: {
			pdd: number;
			bdr: number;
			igpddr: number;
		};
	} = $props();
</script>

<Frame>
	<Stars star={gear.star} maxStar={gear.maxStar} color={gear.starScroll ? 'blue' : 'yellow'} />
	<TitleWrapper>
		<SoulTitle soulName={gear.soul?.name} />
		<NameTitle
			name={gear.name}
			scrollUpgradeCount={gear.scrollUpgradeCount}
			color={gear.scrollUpgradeCount > 0 ? 'red' : 'white'}
		/>
	</TitleWrapper>
	<Spacer height={4} />
	<Grade grade={gear.potentialGrade} specialGrade={gear.attributes.specialGrade} />
	<Attributes
		only={gear.attributes.only}
		trade={gear.attributes.trade}
		onlyEquip={gear.attributes.onlyEquip}
		share={gear.attributes.share}
		blockGoldenHammer={gear.attributes.blockGoldenHammer}
		canPotential={gear.attributes.canPotential}
	/>
	<Spacer height={10} />
	<DotLine />
	<SummaryWrapper>
		<IconWrapper>
			<Icon icon={gear.shapeIcon} grade={gear.potentialGrade} />
		</IconWrapper>
		<SummaryDetailWrapper>
			{#if 'attack' in incline && 'combat' in incline}
				<Incline label="공격력 증가량" diff={incline.attack} small />
				<Incline label="전투력 증가량" diff={incline.combat} small />
			{:else if 'attack' in incline}
				<Incline label="공격력 증가량" diff={incline.attack} />
			{:else if 'combat' in incline}
				<Incline label="전투력 증가량" diff={incline.combat} />
			{/if}
			<Spacer height={1} />
			<ReqWrapper>
				<ReqRow>
					<ReqLevel value={gear.req.level} vary={-gear.addOption.reqLevelDecrease} can />
				</ReqRow>
				<Spacer height={9} />
				<ReqRow>
					<ReqStat type="str" value={gear.req.str} can />
					<ReqStat type="luk" value={gear.req.luk} can />
				</ReqRow>
				<Spacer height={3} />
				<ReqRow>
					<ReqStat type="dex" value={gear.req.dex} can />
					<ReqStat type="int" value={gear.req.int} can />
				</ReqRow>
			</ReqWrapper>
		</SummaryDetailWrapper>
	</SummaryWrapper>
	<Spacer height={5} />
	<DiffExtraWrapper>
		<DiffExtra type="pdd" value={diff.pdd} />
		<DiffExtra type="bdr" value={diff.bdr} percent />
		<DiffExtra type="igpddr" value={diff.igpddr} percent />
	</DiffExtraWrapper>
	<Spacer height={3} />
	<JobReq reqJob={gear.req.job} can message={getExtraJobReqString(gear.type)} />
	<Spacer height={9} />
	<DotLine />
	<Spacer height={4} />
</Frame>
