// src/entities/gear-tooltip/ui/components/Frame.svelte
<script lang="ts">
	import { UIImage } from '$lib/shared/ui';
	import type { Snippet } from 'svelte';

	let { children, class: className }: { children?: Snippet; class?: string } = $props();
</script>

<div class={['relative w-[324px]', className]} style="image-rendering: pixelated;">
	<UIImage image="frameTop" />
	<UIImage image="frameLine" class="flex flex-col items-center" style="height: unset;">
		{@render children?.()}
	</UIImage>
	<UIImage image="frameBottom" />
	<UIImage image="frameCover" class="absolute top-0 left-0" />
</div>

// src/entities/tooltip/ui/Frame.tsx
import { frameBottom, frameCover, frameLine, frameTop } from "@/shared/ui";
import { clsx } from "@/shared/util";

export function Frame({
  children,
  className,
}: Readonly<{ children: React.ReactNode; className?: string }>) {
  return (
    <div className={clsx("w-[261px] relative", className)}>
      <div className="h-[13px] bg-no-repeat" style={{ backgroundImage: `url(${frameTop.src})` }} />
      <div
        className="flex flex-col items-center bg-repeat-y"
        style={{ backgroundImage: `url(${frameLine.src})` }}
      >
        {children}
      </div>
      <div
        className="h-[13px] bg-no-repeat"
        style={{ backgroundImage: `url(${frameBottom.src})` }}
      />
      <div
        className="w-[53px] h-[43px] bg-no-repeat absolute top-0 left-0"
        style={{ backgroundImage: `url(${frameCover.src})` }}
      />
    </div>
  );
}
