// src/lib/components/gear-tooltip/components/summary/Incline.svelte
<script lang="ts">
	import UIImage from '../UIImage.svelte';

	let { label, diff, small = false }: { label: string; diff: number; small?: boolean } = $props();

	type Size = '' | '_10digit' | '_8digit';

	const sign = $derived(diff > 0 ? '+' : diff < 0 ? '-' : null);
	const digits = $derived(Math.abs(diff).toString());
	const size = $derived(getSize(small, digits));

	function getSize(small: boolean, digits: string): Size {
		if (small) {
			return '_8digit';
		}
		if (digits.length > 9) {
			return '_8digit';
		} else if (digits.length > 7) {
			return '_10digit';
		} else {
			return '';
		}
	}

	const digitMargins = {
		'': [1, 4, 1, 2, 1, 2, 1, 2, 1, 1],
		_10digit: [0, 1, 1, 1, 0, 0, 0, 0, 0, 0],
		_8digit: [0, 1, 0, 0, -1, 0, 0, 0, 0, 0]
	};
</script>

<div
	class={[
		'flex flex-col items-end',
		{
			'mb-[5px] gap-[4px]': size === '',
			'mb-[8px] gap-[4px]': size === '_10digit',
			'mb-[7px] gap-[2px]': size === '_8digit'
		}
	]}
>
	<div class="gt--detail gt--gray2 whitespace-pre">{label}{' '}</div>
	<div class={['flex items-center justify-end', { '-mr-0.5': size === '_10digit' }]}>
		{#if sign}
			{@render signImage(sign, size)}
		{/if}
		{#each digits.split('') as digit}
			{@render digitImage(digit, size, diff < 0)}
		{/each}
	</div>
</div>

{#snippet signImage(sign: '+' | '-', size: Size)}
	<UIImage
		image={((sign === '+' ? `inclinePlus` : 'declineMinus') + size) as 'inclinePlus'}
		class={[{ 'mr-1': size === '' }]}
	/>
{/snippet}

{#snippet digitImage(digit: string, size: Size, isDecline: boolean)}
	<UIImage
		image={((isDecline ? 'decline' : 'incline') + digit + size) as 'incline0'}
		style="margin-left: {digitMargins[size][Number(digit)]}px"
	/>
{/snippet}

// src/entities/tooltip/ui/Incline.tsx
import {
  decline0,
  decline1,
  decline2,
  decline3,
  decline4,
  decline5,
  decline6,
  decline7,
  decline8,
  decline9,
  decline_10digit0,
  decline_10digit1,
  decline_10digit2,
  decline_10digit3,
  decline_10digit4,
  decline_10digit5,
  decline_10digit6,
  decline_10digit7,
  decline_10digit8,
  decline_10digit9,
  decline_10digitMinus,
  decline_8digit0,
  decline_8digit1,
  decline_8digit2,
  decline_8digit3,
  decline_8digit4,
  decline_8digit5,
  decline_8digit6,
  decline_8digit7,
  decline_8digit8,
  decline_8digit9,
  decline_8digitMinus,
  declineMinus,
  incline0,
  incline1,
  incline2,
  incline3,
  incline4,
  incline5,
  incline6,
  incline7,
  incline8,
  incline9,
  incline_10digit0,
  incline_10digit1,
  incline_10digit2,
  incline_10digit3,
  incline_10digit4,
  incline_10digit5,
  incline_10digit6,
  incline_10digit7,
  incline_10digit8,
  incline_10digit9,
  incline_10digitPlus,
  incline_8digit0,
  incline_8digit1,
  incline_8digit2,
  incline_8digit3,
  incline_8digit4,
  incline_8digit5,
  incline_8digit6,
  incline_8digit7,
  incline_8digit8,
  incline_8digit9,
  incline_8digitPlus,
  inclinePlus,
} from "@/shared/ui";
import { clsx } from "@/shared/util";
import { UIImage } from "./UIImage";
import styles from "./tooltip.module.css";

type Size = "normal" | "10digit" | "8digit";

export default function Incline({
  label,
  diff,
  small = false,
}: Readonly<{
  label: string;
  diff: number;
  small?: boolean;
}>) {
  const sign = diff > 0 ? "+" : diff < 0 ? "-" : null;
  const digits = Math.abs(diff).toString();
  const size = getSize(small, digits);

  return (
    <div
      className={clsx("flex flex-col items-end", {
        "gap-[4px] mb-[5px]": size === "normal",
        "gap-[4px] mb-[8px]": size === "10digit",
        "gap-[2px] mb-[7px]": size === "8digit",
      })}
    >
      <div className={clsx("whitespace-pre", styles.detailText, styles.gray2)}>{label} </div>
      <div className={clsx("flex items-center justify-end", { "-mr-[2px]": size === "10digit" })}>
        {sign ? <Sign sign={sign} size={size} /> : null}
        {digits.split("").map((digit, i) => (
          <Digit digit={digit} size={size} isDecline={sign === "-"} key={i} />
        ))}
      </div>
    </div>
  );
}

function Sign({ sign, size }: Readonly<{ sign: "+" | "-"; size: Size }>) {
  const image = signImages[size][sign];
  const margin = signMargins[size];
  return <UIImage image={image} style={{ marginLeft: `${margin}px` }} />;
}

function Digit({
  digit,
  size,
  isDecline,
}: Readonly<{ digit: string; size: Size; isDecline: boolean }>) {
  const images = isDecline ? declineImages : inclineImages;
  const image = images[size][digit as keyof (typeof images)["normal"]];
  const margin = digitMargins[size][digit as keyof (typeof digitMargins)["normal"]];
  return <UIImage image={image} style={{ marginLeft: `${margin}px` }} />;
}

function getSize(small: boolean, digits: string) {
  if (small) {
    return "8digit";
  }
  if (digits.length > 9) {
    return "8digit";
  } else if (digits.length > 7) {
    return "10digit";
  } else {
    return "normal";
  }
}

const signImages = {
  normal: {
    "+": inclinePlus,
    "-": declineMinus,
  },
  "10digit": {
    "+": incline_10digitPlus,
    "-": decline_10digitMinus,
  },
  "8digit": {
    "+": incline_8digitPlus,
    "-": decline_8digitMinus,
  },
};

const inclineImages = {
  normal: {
    "0": incline0,
    "1": incline1,
    "2": incline2,
    "3": incline3,
    "4": incline4,
    "5": incline5,
    "6": incline6,
    "7": incline7,
    "8": incline8,
    "9": incline9,
  },
  "10digit": {
    "0": incline_10digit0,
    "1": incline_10digit1,
    "2": incline_10digit2,
    "3": incline_10digit3,
    "4": incline_10digit4,
    "5": incline_10digit5,
    "6": incline_10digit6,
    "7": incline_10digit7,
    "8": incline_10digit8,
    "9": incline_10digit9,
  },
  "8digit": {
    "0": incline_8digit0,
    "1": incline_8digit1,
    "2": incline_8digit2,
    "3": incline_8digit3,
    "4": incline_8digit4,
    "5": incline_8digit5,
    "6": incline_8digit6,
    "7": incline_8digit7,
    "8": incline_8digit8,
    "9": incline_8digit9,
  },
};

const declineImages = {
  normal: {
    "0": decline0,
    "1": decline1,
    "2": decline2,
    "3": decline3,
    "4": decline4,
    "5": decline5,
    "6": decline6,
    "7": decline7,
    "8": decline8,
    "9": decline9,
  },
  "10digit": {
    "0": decline_10digit0,
    "1": decline_10digit1,
    "2": decline_10digit2,
    "3": decline_10digit3,
    "4": decline_10digit4,
    "5": decline_10digit5,
    "6": decline_10digit6,
    "7": decline_10digit7,
    "8": decline_10digit8,
    "9": decline_10digit9,
  },
  "8digit": {
    "0": decline_8digit0,
    "1": decline_8digit1,
    "2": decline_8digit2,
    "3": decline_8digit3,
    "4": decline_8digit4,
    "5": decline_8digit5,
    "6": decline_8digit6,
    "7": decline_8digit7,
    "8": decline_8digit8,
    "9": decline_8digit9,
  },
};

const signMargins = {
  normal: 4,
  "10digit": 0,
  "8digit": 0,
};

const digitMargins = {
  normal: {
    "0": 1,
    "1": 4,
    "2": 1,
    "3": 2,
    "4": 1,
    "5": 2,
    "6": 1,
    "7": 2,
    "8": 1,
    "9": 1,
  },
  "10digit": {
    "0": 0,
    "1": 1,
    "2": 1,
    "3": 1,
    "4": 0,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
  },
  "8digit": {
    "0": 0,
    "1": 1,
    "2": 0,
    "3": 0,
    "4": -1,
    "5": 0,
    "6": 0,
    "7": 0,
    "8": 0,
    "9": 0,
  },
};
