// src/entities/tooltip/ui/Stars.tsx
import { blueStar, emptyStar, yellowStar } from "@/shared/ui";
import { UIImage } from "./UIImage";

export function Stars({
  star,
  maxStar,
  color = "yellow",
}: Readonly<{ star: number; maxStar: number; color?: "yellow" | "blue" }>) {
  const lines = toStarArray(star, maxStar);

  if (lines.length === 0) {
    return null;
  }

  return (
    <div className="flex flex-col items-center gap-[8px] mb-[8px]">
      {lines.map((line, l) => (
        <div className="h-[10px] flex gap-[6px] pr-[1px]" key={l}>
          {line.map((group, g) => (
            <div className="flex items-start" key={g}>
              {group.map((lit, s) => (
                <Star color={color} isEmpty={!lit} key={s} />
              ))}
            </div>
          ))}
        </div>
      ))}
    </div>
  );
}

function Star({ color, isEmpty }: Readonly<{ color: string; isEmpty: boolean }>) {
  let image;
  if (isEmpty) {
    image = emptyStar;
  } else {
    image = color === "yellow" ? yellowStar : blueStar;
  }
  return <UIImage image={image} style={{ marginRight: "-1px" }} />;
}

const STAR_PER_LINE = 15;
const STAR_PER_GROUP = 5;

function toStarArray(star: number, maxStar: number) {
  maxStar = Math.max(star, maxStar);
  const lines = [];
  for (let l = 0; l < maxStar; l += STAR_PER_LINE) {
    const line = [];
    for (let g = l; g < Math.min(maxStar, l + STAR_PER_LINE); g += STAR_PER_GROUP) {
      const group = [];
      for (let s = g; s < Math.min(maxStar, g + STAR_PER_GROUP); s++) {
        group.push(s < star);
      }
      line.push(group);
    }
    lines.push(line);
  }
  return lines;
}

// src/lib/components/gear-tooltip/components/Stars.svelte
<script lang="ts">
	import UIImage from './UIImage.svelte';

	let { star, maxStar, color }: { star: number; maxStar: number; color: 'yellow' | 'blue' } =
		$props();

	const STAR_PER_LINE = 15;
	const STAR_PER_GROUP = 5;

	const lines = $derived(toStarArray(star, maxStar));

	function toStarArray(star: number, maxStar: number) {
		maxStar = Math.max(star, maxStar);
		const lines = [];
		for (let l = 0; l < maxStar; l += STAR_PER_LINE) {
			const line = [];
			for (let g = l; g < Math.min(maxStar, l + STAR_PER_LINE); g += STAR_PER_GROUP) {
				const group = [];
				for (let s = g; s < Math.min(maxStar, g + STAR_PER_GROUP); s++) {
					group.push(s < star);
				}
				line.push(group);
			}
			lines.push(line);
		}
		return lines;
	}
</script>

{#if lines}
	<div class="flex flex-col items-center">
		{#each lines as line}
			<div class="mb-2 flex h-2.5 gap-1.5 pl-px">
				{#each line as group}
					<div class="flex">
						{#each group as isFilled}
							{@render starIcon(color, !isFilled)}
						{/each}
					</div>
				{/each}
			</div>
		{/each}
	</div>
{/if}

{#snippet starIcon(color: 'yellow' | 'blue', isEmpty: boolean)}
	{#if isEmpty}
		<UIImage image="emptyStar" class="-mr-px" />
	{:else if color === 'yellow'}
		<UIImage image="yellowStar" class="-mr-px" />
	{:else}
		<UIImage image="blueStar" class="-mr-px" />
	{/if}
{/snippet}
